## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'. # Dropped "SPECIAL_CONSIDERATIONS" and "STATUS" for optimization.
application_df = application_df.drop(['EIN', 'NAME', "SPECIAL_CONSIDERATIONS", "STATUS" ], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
  # Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 100
app_type = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = list(app_type[app_type < cutoff].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_type = application_df['CLASSIFICATION'].value_counts()
final_class = class_type[class_type > 1]
final_class

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_cutoff = 100
classifications_to_replace = list(class_type[class_type < class_cutoff].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
n_application_df = pd.get_dummies(application_df)
n_application_df.head()

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,False,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,108590,1,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,5000,0,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,6692,1,False,False,False,True,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,142590,1,False,False,False,True,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False

In [10]:
# Split our preprocessed data into our features and target arrays
X = n_application_df.drop("IS_SUCCESSFUL", axis=1).values
y = n_application_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# Number of input features
input_features = len(X_train[0])

# First hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               4800

 dense_1 (Dense)             (None, 100)               10100

 dense_2 (Dense)             (None, 100)               10100

 dense_3 (Dense)             (None, 1)                 101

=================================================================
Total params: 25101 (98.05 KB)
Trainable params: 25101 (98.05 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5680 - accuracy: 0.7186
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5528 - accuracy: 0.7301
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7308
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7332
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7327
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7332
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7344
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7365
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7357
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7359
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7365
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7360
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7361
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7372
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7372
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7380
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7383
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7386
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7389
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7402
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7382
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7381
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7394
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7398
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7398
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7397
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7399
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7398
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7406
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7400
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7399
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7398
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7401
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7406
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7398
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5337 - accuracy: 0.7400
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7409
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7408
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7408
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7412
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7402
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7408
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7409
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7408
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7414
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7405
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7412
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7407
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7414
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7415
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7413
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7414
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7417
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7411
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7420
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7416
Epoch 60/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5302 - accuracy: 0.7411
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7418
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7413
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7412
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7418
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7413
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7414
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5296 - accuracy: 0.7413
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7419
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7423
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7419
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7417
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7413
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7412
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.7416
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7418
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7421
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7420
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7419
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7418
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7418
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7411
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5284 - accuracy: 0.7420
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7414
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7418
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7421
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7421
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7419
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7420
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5286 - accuracy: 0.7420
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7419
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7414
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7421
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7421
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7422
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7418
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5282 - accuracy: 0.7426
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5283 - accuracy: 0.7418
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5281 - accuracy: 0.7420
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7414
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7421

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5996 - accuracy: 0.7285 - 1s/epoch - 5ms/step
Loss: 0.5995520353317261, Accuracy: 0.7285131216049194

In [16]:
# Export our model to HDF5 file
nn.save('h5Files/AlphabetSoupCharityOptimization1.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(